cisco-open/stated

package.json
Provide export for commonjs bundle in package.json
=> export commonjs bundle

src/CliCore.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/test/StatedREPL.test.js
Minor improvements for StatedREPL, required for stated workflows. 
* onInit to execute customer-provided callback
* custom print function to stringify
* stringify resp
tests.
=> onInit, stringify custom print function, stringify resp in cli

README.test.js, src/TestUtils.ts
=> move README tests to TestUtils

package.json, src/test/TemplateProcessor.test.js
export DependencyFinder to use in 3rd party packages
=> export DependencyFinder

src/CliCore.ts, src/StatedREPL.ts
=> add tp in StatedREPL and CLICore constructor

package.json
export debounce function
version++
=> export debounce func

README.md, example/absoluteRoot.json, example/context.json, example/ex16.json, example/experimental/main.yaml, example/experimental/main2.yaml, example/importsAbsoluteRoot.json, src/CliCore.ts, src/MetaInfoProducer.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
see readme
- [ x] Documentation
=> Dynamic imports

README.md, example/ex21.json, src/CliCore.ts, src/DependencyFinder.ts, src/StatedREPL.ts, src/TestUtils.ts, src/VizGraph.ts, src/test/DependencyFinder.test.js, src/test/VizGraph.test.js
various fixes associated with improving SVG output
- [ x] Bug Fix
- [ x] Documentation
=> Various fixes

package.json, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
crap, forgot to merge this! 0.1.5 already contains changes from this branch. Apparently forgot to merge.
=> Data change callback op

src/ConsoleLogger.ts, src/Debugger.ts, src/FancyLogger.ts, src/MetaInfoProducer.ts, src/TestUtils.ts, src/TimerManager.ts, src/VizGraph.ts, src/utils/debounce.ts, src/utils/stringify.ts
=> +Cisco Copyright

README.md, example/concurrent-homeworlds.json, example/ex21.json, example/ex22.json, example/ex22.yaml, example/homeworlds.json, src/test/DependencyFinder.test.js, src/test/TemplateProcessor.test.js
Mostly s/swapi.dev/swapi.tech/
But also a small change in search APIs
```
-  "luke": "${ call('https://swapi.dev/api/people/?search=luke').results[0].name}",
+  "luke": "${ call('https://swapi.tech/api/people/?name=luke').result[0].properties.name}",
```
=> swapi dev to tech migration

src/MetaInfoProducer.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
allow import of raw expression strings
=> initial commit of feature

src/ExecutionStatus.ts, src/TemplateProcessor.ts
few unpushed change that i forgot
=> Kill non concurrent safe did update meta

.github/workflows/test.yml, package-lock.json, package.json, src/test/Pulsar.test.js, yarn.lock
added a basic pulsar test, and modified package.json files stanza so that npm package doesn't contain cruft.
=> hello pulsar

package.json, src/index.d.ts
for correct "import TemplateProcessor from 'stated-js'" from within a TS file, there should be index.d.ts
- [X ] Other (please describe)
=> add index.d.ts

package.json, src/index.d.ts
adjust package.json 'types' to point to dist/src/index.d.ts
=> Index d ts

package.json, src/TemplateProcessor.ts, src/index.d.ts
make template uniqueId stronger. Fix index.d.ts exports.
- [ x] Other (please describe)
=> fix exports, better uuid for templates

package.json
remove src dir from package root, bump version
=> remove src dir from package root

example/importme.txt, package.json, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
=> import text

package.json, src/CliCoreBase.ts
=> Support open txt

package.json, src/TemplateProcessor.ts, src/index.d.ts, src/test/TemplateProcessor.test.js
export Lifecycle stuff from package
=> Export lifecycle

README.md, example/accumulate1.json, package.json, src/MetaInfoProducer.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js, src/utils/GeneratorManager.ts, src/utils/accumulate.ts, src/utils/default.ts
introduces $accumulator function
=> accumulate

package.json, src/CliCoreBase.ts, src/DataFlow.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
=> flow command

package.json, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
see test "test import with props" ...  allows a template to $import(template, props)
- [x ] New code contribution is covered by automated tests
- [ x] All new and existing tests pass
=> Import with props

package.json, src/test/TemplateProcessor.test.js, src/utils/stringify.ts
fix stringify so it does not elide async functions
- [ x] Bug Fix
- [x ] All new and existing tests pass
=> Stringify async function

.github/workflows/test.yml, .github/workflows/test_bun.yml, package.json, src/ConsoleLogger.ts, src/ParallelPlanner.ts, src/TemplateProcessor.ts, src/index.ts, src/test/TemplateProcessor.test.js
=> plan_queue_reentrancy_fix_for_imported_templates

package.json, src/TemplateProcessor.ts, src/test/StatedREPL.test.js, src/test/TemplateProcessor.test.js
see new test for $change method
=> added  methood

.github/workflows/test.yml
trying to fix GH_PAT token that we push docs with
- [ x] Bug Fix
=> add echo task
