README.md, README.test.js
* README: Added the `.note` and `.plan` commands to the reference table
* Fixed typo in README.test.js comment
=> Add `.note` and `.plan` to command table

src/MetaInfoProducer.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
hopefully this is not a breaking change and just makes functiond defined in jsonata expression callable like normal functions outside of stated. 
=> +functions defined in jsonata behave normall in js

src/CliCore.ts, src/TemplateProcessor.ts
This change ensures that we can reuse an instance of customized template processor.
=> Reuse template proessor

src/FancyLogger.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/utils/stringify.ts
Refactored stringify and printfn to reuse common util.
=> refactor common function

src/CliCore.ts
```
> .open
Error reading directory /Users/sesergee/projects/sandbox/stated-js/example: Error: ENOENT: no such file or directory, scandir '/Users/sesergee/projects/sandbox/stated-js/example'
Changed directory with .cd or .open an/existing/directory
> .open blah
Error reading directory blah: Error: ENOENT: no such file or directory, scandir 'blah'
Changed directory with .cd or .open an/existing/directory
```
=> catch errors on open

README.md, example/errorReport.json, src/CliCore.ts, src/StatedREPL.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
https://github.com/cisco-open/stated/issues/31
adds $errorReport function
- [ x] Documentation
- [ x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ x] Existing issues have been referenced (where applicable)
- [ x] I have verified this change is not present in other open pull requests
- [ x] Functionality is documented
- [ x] All code style checks pass
- [ x] New code contribution is covered by automated tests
- [ x] All new and existing tests pass
=> +errorReport

README.md, example/importLocal.json, src/CliCore.ts, src/TestUtils.ts
$open function 
closes https://github.com/cisco-open/stated/issues/32
- [ X] New Feature
- [ X] Documentation
- [ X] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [X ] Existing issues have been referenced (where applicable)
- [X ] I have verified this change is not present in other open pull requests
- [X ] Functionality is documented
- [ X] All code style checks pass
- [ X] New code contribution is covered by automated tests
- [ X] All new and existing tests pass
=> + ++README

src/CliCore.ts, src/JsonPointer.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
add prepareSnapshot method, and basic test. Verifies that data set into template output, and emitted in snapshot output is merged back into template when the snapshot is prepared.
- [ x] Bug Fix
=> add prepareSnapshot

.github/workflows/test.yml, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
make sure snapshots cannot be emitted when plan execution in progress (output has not stabilized). Snapshot() becomes async.
- [x ] Refactor
=> Consistent snapshots

webpack.config.cjs.js, webpack.config.js
Joshua and I came across type errors when trying to upgrade to stated@0.0.98+. I think there was a folder name typo in https://github.com/cisco-open/stated/commit/a86478a05e6c41d73e0c7ecf415764301d24e540 that caused the type exports to get dropped and the *.ts files to get exported instead.  
- [ x] Bug Fix
=> Fix missing types export

package.json, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
make sure no-change plans abort early. Include test to make sure no-change plan does not trigger any onDataChange callbacks
- [ x] Bug Fix
=> Dashify integration fixes march 22 2024

src/ExecutionStatus.ts, src/TemplateProcessor.ts
using MetaInfo.didUpdate__ was not fork sage. Killed it off and moved didUpdate into fork safe constructs.
- [x ] Bug Fix
- [x ] Refactor
=> kill off didUpdate__

README.md, README.test.js, example/ex24.json, src/CliCore.ts, src/ExecutionStatus.ts, src/TemplateProcessor.ts, src/TestUtils.ts, src/TimerManager.ts, src/test/CliCore.test.js, src/test/StatedREPL.test.js, src/test/TemplateProcessor.test.js, src/utils/env.ts
support $env('myVar') to get vars from node env. 
- [ x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ x] Existing issues have been referenced (where applicable)
- [ x] I have verified this change is not present in other open pull requests
- [ x] Functionality is documented
- [ x] All code style checks pass
- [ x] New code contribution is covered by automated tests
- [ x] All new and existing tests pass
=> Env Function

package.json, src/index.ts, webpack.config.cjs.js, webpack.config.js
package.json and webpack configs should point to index as the main, since that is where all the exports are that define the module
- [ x] Bug Fix
=> fix main entrypoint

package.json, src/CliCore.ts, src/StatedREPL.ts, src/test/CliCore.test.js, src/test/StatedREPL.test.js
=> Fix repl open

README.md, example/generate.json, example/myGenerator.json, example/myGenerator.mjs, example/myGenerator2.json, src/TemplateProcessor.ts, src/TimerManager.ts, src/test/TemplateProcessor.test.js, src/utils/GeneratorManager.ts
Add support and documentation for generators.
Fix bug - initial plan should be queued to prevent side-effect interference (timers, generators, etc) from borking the initial template execution.
all tests pass, docs enhances, cleanups
=> generators

README.md, example/generate.json, package.json, src/Lifecycle.ts, src/LifecycleManager.ts, src/TemplateProcessor.ts, src/index.ts, src/test/TemplateProcessor.test.js
add general purpose (extensible) lifecycle hooks so we never have to add specific lifecycle methods like "onInit" again.
=> Lifecycle hooks

package.json, src/JsonPointer.ts, src/TemplateProcessor.ts, src/test/TemplateProcessor.test.js
When setData is called, a set of changes (a DAG) is calculated and the changes are sequentially applied. These
changes can be 'bundled' into a single Transaction for the purpose of capturing a single set of changes that
if atomically applied, has the exact same effect as the DAG propagation. Therefore, a Transaction can be a
less chatty way to capture and apply changes from one template instance A to template instance B without
incurring the cost of for B to compute the change DAG.  
=> transactions

README.md, example/importLocalJsModule.yaml, example/myModule.mjs, package.json, src/CliCoreBase.ts, src/JsonPointer.ts, src/TemplateProcessor.ts, src/VizGraph.ts, src/test/TemplateProcessor.test.js, src/utils/GeneratorManager.ts, src/utils/stringify.ts
allow direct $import of mjs (see README)
=> direct js import

package.json, src/utils/GeneratorManager.ts
systems like pulsar subscriber can exit/break without returning a val…ue, and will generate {done:true, value:undefined} which should not be pumped
=> don't pump undefined items on done

package.json, src/ParallelExecutionPlanDefault.ts, src/ParallelPlanner.ts, src/TemplateProcessor.ts, src/TraversalState.ts, src/test/TemplateProcessor.test.js
it was possible that there could be race conditions in parallel plans, because the _execute promise started before it was put in the promises map. This code fixes it, and deals with deadlocks that happen in circular plans by adding circular:boolean to the PlanStep so that execution can be stopped when circularity is detected.
- [x ] New code contribution is covered by automated tests
=> improve execute to eliminate race conditions

.github/workflows/test.yml, README.md, example/ex25.json, example/ex26.json, src/MetaInfoProducer.ts, src/test/MetaInfoProducer.test.js
Minor update to avoid expression evaluation when the path key starts with "⛔".
=> Add 'no_entry' emoji to avoid expression evaluation
